#!/bin/bash -eu

if [ "$(uname)" == "Darwin" ]; then
  # impure for symlinking lazyvim config from dotfiles directory to XDG config
  nix build \
    --extra-experimental-features 'nix-command flakes' \
    .#darwinConfigurations."Jonathans-MacBook-Pro".system
  ./result/sw/bin/darwin-rebuild switch --impure --flake .
else
  export NIXPKGS_ALLOW_BROKEN=1
  home-manager switch --flake .#$(hostname) \
    --extra-experimental-features 'nix-command flakes'
fi
